authorName: default
experimentName: Auto Hyperparameter Tuning4
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 100
trainingServicePlatform: local  # choices: local, remote, pai
searchSpacePath: search_space.json
useAnnotation: false
tuner:
    builtinTunerName: TPE   # choices: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner,
                            #          GPTuner, SMAC (SMAC should be installed through nnictl)
    classArgs:
        optimize_mode: maximize  # choices: maximize, minimize
trial:
  command: python3 train.py
  codeDir: .
  gpuNum: 1
